### ISSUE TITLE
dsmr.available() remains false

### ISSUE THREAD

**Issue by ErwinP** [mrWheel/arduino-dsmr-be#1]
Hi,

First of all: thanks a BUNCH for making this library available!

I'm trying to [replicate a project](https://github.com/schnef/dsmr-mqtt) in which the DSMR data is being read by an Adafruit ESP8266 breakout board, and subsequently being sent to my MQTT broker. The original project makes use of the "original" arduino-dsmr library, and I assume that I could just swap libraries with yours, to make this work.

At the hardware side, everything seems to be set up correctly: the board boots and initial (debug) messages are broadcasted of MQTT. However, the call for` dsmr.available()` remains false. This could be a consequence of wiring, which is why I [asked advice from schnef](https://github.com/schnef/dsmr-mqtt/issues/2). Aternatively, I could be using the library in the wrong way... which is why I'm asking advice here :)

Am I correct that all I needed to do to get this working, is

1. Copy the dsmr-be library into the library folder of the Arduino IDE
2. Replace` #include "dsmr.h"` by `#include "dsmr-be.h"`
3. Upload the code

Thanks a lot in advance for giving this some attention!

Kind regards,
Erwin

(Current code: https://github.com/ErwinP/dsmr-mqtt)

**Comment by mrWheel** [comment]
The dsmr-be library is depreciated.
You better use dsmr2Lib for your projects.
