### ISSUE TITLE
Error parsing telegrams Fluvius: Issue with field definition

### ISSUE THREAD

**Issue by klenaers** [mrWheel/arduino-dsmr-be#3]
Hi,

Thanks for creating this library and make it available! 
Everything was working perfectly until this morning. The P1-messages weren't getting parsed correctly.

After some debugging I found that the Fluvius changed their P1 version to 50215 and that the Ampère-values per phase are there.
/FLU5\253769400_A

0-0:96.1.4(50215)
0-0:96.1.1(--------------)
0-0:1.0.0(210213112714W)
1-0:1.8.1(000168.180*kWh)
1-0:1.8.2(000194.905*kWh)
1-0:2.8.1(000035.833*kWh)
1-0:2.8.2(000006.354*kWh)
0-0:96.14.0(0002)
1-0:1.7.0(01.659*kW)
1-0:2.7.0(00.000*kW)
1-0:21.7.0(00.000*kW)
1-0:41.7.0(03.605*kW)
1-0:61.7.0(00.351*kW)
1-0:22.7.0(02.297*kW)
1-0:42.7.0(00.000*kW)
1-0:62.7.0(00.000*kW)
1-0:32.7.0(237.8*V)
1-0:52.7.0(235.2*V)
1-0:72.7.0(238.7*V)
1-0:31.7.0(009.68*A)
1-0:51.7.0(015.33*A)
1-0:71.7.0(002.04*A)
0-0:96.3.10(1)
0-0:17.0.0(999.9*kW)
1-0:31.4.0(999*A)
0-0:96.13.0()
0-1:24.1.0(003)
0-1:96.1.1(-------------)
0-1:24.4.0(1)
0-1:24.2.3(210213112500W)(00227.504*m3)
!5725

I changed this part of the code in file fields-be.h and now it works again.

/* Instantaneous current L1 in A resolution */
//DEFINE_FIELD(current_l1, uint16_t, ObisId(1, 0, 31, 7, 0), IntField, units::A);
DEFINE_FIELD(current_l1, FixedValue, ObisId(1, 0, 31, 7, 0), FixedField, units::A,units::A);
/* Instantaneous current L2 in A resolution */
//DEFINE_FIELD(current_l2, uint16_t, ObisId(1, 0, 51, 7, 0), IntField, units::A);
DEFINE_FIELD(current_l2, FixedValue, ObisId(1, 0, 51, 7, 0), FixedField, units::A, units::A);
/* Instantaneous current L3 in A resolution */
//DEFINE_FIELD(current_l3, uint16_t, ObisId(1, 0, 71, 7, 0), IntField, units::A);
DEFINE_FIELD(current_l3, FixedValue, ObisId(1, 0, 71, 7, 0), FixedField, units::A, units::A);

I hope this helps the other users that have this issue.

**Comment by wassup-** [comment]
I noticed the same thing. Congrats on finding a solution yourself!

To improve on your current solution, the correct definitions would be
```
DEFINE_FIELD(current_l1, FixedValue, ObisId(1, 0, 31, 7, 0), FixedField, units::A, units::mA);
DEFINE_FIELD(current_l2, FixedValue, ObisId(1, 0, 51, 7, 0), FixedField, units::A, units::mA);
DEFINE_FIELD(current_l3, FixedValue, ObisId(1, 0, 71, 7, 0), FixedField, units::A, units::mA);
```

Because as the documentation of `FixedField` states 
> To prevent inefficient floating point operations, we store them as a fixed-point number: an integer that stores the value in thousands. For example, a value of 1.234 kWh is stored as 1234.

**Comment by wijnanb** [comment]
Created a PR for this https://github.com/mrWheel/arduino-dsmr-be/pull/4

**Comment by mrWheel** [comment]
The dsmr-be library is depreciated.
You will find the same functionality and than some in dsmr2Lib.
